### ISSUE TITLE
EKS-helm - remove channel feature

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/EKS-helm#10]
## User Story

**As a** Tazama system operator
**I want** to remove the channel feature
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

**Impact assessment** required to determine if this repository is impacted by removing the channel feature

#acceptance criteria
1. Pull from dev branch
2. Update references to renamed processors - Rename the channel-router-setup-processor to event-director
3. Deployment testing
4. Integration testing

## Identified impacts:
1. Rename the `crsp` NATS subject to `event-director`

**Comment by vorsterk** [comment]
Tested on microkubes . Working E2E . Changes needed to be made to on postman repo for the Arangodb setup collection.
